travis:
  secure:
    BINSTAR_TOKEN: ipY9K/r81PsePdJ82N1tIkDa1d94cY0DB2nNqz67IgTxUGcRZFFJjZ7dXUNmWOOj108sTsnKCfAutsTNx6wsqZpDmTYGf+tVH0rs86p/o6dPdVV4UytGX71C0FDbjGbLxm4T3SGe2zeRerbkNrFDz3ASigOD3CXACRzAEKlAX/hqnez69NCv/Ha0gRolDm+4n4tp2o8nqANoABN4ht7ISkgT2NDgsDBjSuYCnhz2g5ftWI5NWxDgxe4XldBRmzq7SWfoYLAcE+4DLbobzAnqk5v3LVLjtDwTAFf6d9/tpaj8E+Hf0OwdO1xPWFm+RxfS8J6Kh0XhzSlW3MQBqMkyLAq+0SdZZGgcquxtVCzlBa4kaW+/E6YLZX/cJpVPW46vlKO2nC3SoMjXdwF3bf9WXGotKQGB0/wPh6IusWuaSP9rWNYCtQfPnDhcXgwijMerknQSGqMovuE70a3/xTzFD7+LHggUoHSHlknzInJUtTvAGVM6LH2rcZs4plpjLtrVu0hy9thnOjmP4f1YkuClQHU/vhbFIYvMXEL+gpNUgAX8yuBouVTWfT/UQNrzagGchtW9DVQHhvthkJnRtezghaAdBiLdKAUbBpYa+lGG18AVTk3VoPJHVLmx99IZt02Ho4GiNP/DlpT7O8K+ePVejM7VkfQMrT78hTKhsmUGuow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
