travis:
  secure:
    BINSTAR_TOKEN: dIwfJVakYCnT1H4sA2a/Xn0l6V7o/EtmyMHBDm1NIUAMXKoWmQ2zrupUoHamlug34q5DdBaTz4FeykWSdCqIXB9YjDYl5C59vf+4c2fL/aJxiEQXjxL7+nHxwWIT0HW+Nh+9ZXDXKKWAVdWiQrfhpu7iEAY8X0GUqPmOU5b3aiYnuwPD/SFoBzd04RIYAzBmXSL+ePR7al5xfd+SBZB5XCiuInmFcpaLomhnhtF3RLvVUdxbPcH7PlXex0SENBuGymBSGJMGwiIh56Bp/icg7hEv98bHoWzUDya7EMhcg7QyvhxnknD207mOpfhNf5J1iedXggzyUMTgl8uwUlf+4OJef6/Pde/j46rQxRWSnO3YwmVD0HO1s2tepjWBz2wE7D1yq4XD3iTo0gAjpKsqMB4bNwMxTgXx+BrWdk2AOoHZEgftaBPx+FVIch5IitJglM3645I0ONPpyNosRz6Qbrj//VA1fE3IVmWdwKZnU5Nhi09TVc/8br0y4rcOWH5kax/DpzFMt27MX8ZeYjBVi+n9NXOXUMKt/SDanBOMZPpj7io1MT+90oi0uUJd7O2E7+K3u0Kt9dOegKXMuztb6dNnRcPrjlqaOF6dbKdjz2dFcXOybiDf4Cg5Z3Vy6P2+FlHv0e/Mp30dILzA5gMUl5ZhkelJPjXF6XPikT9RkiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
